spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://mysql_db_accounts:3306/db_accounts
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always

message: hello, update busrefresh, webhook

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: accounts
    description: mvsvc accounts
    version: v2

logging:
  level:
    com:
      pblgllgs:
        accounts: DEBUG

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345