spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://localhost:3306/db_accounts
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always

message: hello, update busrefresh, webhook

management:
  endpoints:
    web:
      exposure:
        include: '*'
