spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3308/db_cards
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: cards
    description: mvsvc cards
    version: v2

logging:
  level:
    com:
      pblgllgs:
        cards: DEBUG

build:
  version: "3.0"

cards:
  message: "cards related local APIs "
  contactDetails:
    name: "pblgllgs - Developer"
    email: "pblgllgs@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932