spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://localhost:3306/db_cards
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always
management:
  endpoints:
    web:
      exposure:
        include: '*'