spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://mysql_db_loans:3307/db_loans
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
