spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://mysql_db_loans:3306/db_loans
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: loans
    description: mvsvc loans
    version: v2

logging:
  level:
    com:
      pblgllgs:
        loans: DEBUG

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934