spring:
  application:
    name: loans
  datasource:
    url: jdbc:postgresql://postgres_db_loans:5431/db_loans
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
