spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://mysql_db_loans:3306/db_loans
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

info:
  app:
    name: accounts
    description: mvsvc accounts
    version: v2